#!/bin/bash

DEBUG=false
DISABLE_TRANSCODING=true
PLEX_LIBRARY_PATH='/var/lib/plexmediaserver/Library'

if $DEBUG; then
    [[ -d '/tmp/plex_custom_transcoder' ]] || mkdir -p '/tmp/plex_custom_transcoder'
    LOG="/tmp/plex_custom_transcoder/$(date +%Y-%m-%d_%H:%M:%S.%s)"

    echo "# $(date)" > "$LOG"
    echo "# -----------" >> "$LOG"
    echo "cd '$PWD';" >> $LOG
    echo "LD_LIBRARY_PATH='$LD_LIBRARY_PATH';" >> "$LOG"
    echo "EAE_ROOT='$EAE_ROOT';" >> "$LOG"
    echo "FFMPEG_EXTERNAL_LIBS='$FFMPEG_EXTERNAL_LIBS';" >> "$LOG"
    echo "XDG_CACHE_HOME='$XDG_CACHE_HOME';" >> "$LOG"
    echo "XDG_DATA_HOME='$XDG_DATA_HOME';" >> "$LOG"
    echo "X_PLEX_TOKEN='$X_PLEX_TOKEN';" >> "$LOG"

    echo "'./Plex Transcoder_org' \\" >> "$LOG"
    for i in "$@"; do
        printf "   %q \\\n" "$i" >> "$LOG"
    done
    echo ";" >> "$LOG"
    echo "-----------" >> "$LOG"
fi

echo "$0"

LD_LIBRARY_PATH_ORG="$LD_LIBRARY_PATH"
LD_LIBRARY_PATH=

export DEBUG DISABLE_TRANSCODING PLEX_LIBRARY_PATH LD_LIBRARY_PATH_ORG
exec -a "$0" "$(realpath "$0").py" "$@"
